apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.1.0
        ports:
        - containerPort: 3550
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        env:
#          - name: JAEGER_SERVICE_ADDR
#            value: "jaeger-collector:14268"
           - name: DB_HOST
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: host
           - name: DB_PORT
             value: "3306"
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: Username
           - name: DB_PASS
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: Password
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: database_name
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
