# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: productcatalogservice
        ports:
        - containerPort: 3550
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        env:
#          - name: JAEGER_SERVICE_ADDR
#            value: "jaeger-collector:14268"
           - name: DB_HOST
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: host
           - name: DB_PORT
             value: "3306"
           - name: DB_USER
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: Username
           - name: DB_PASS
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: Password
           - name: DB_NAME
             valueFrom:
               secretKeyRef:
                 name: mysql01-binding
                 key: database_name
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: mysql01-binding
spec:
  instanceRef:
    name: mysql01
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mysql01
spec:
  clusterServiceClassExternalName: google-cloudsql-mysql
  clusterServicePlanExternalName: mysql-db-f1-micro
  parameters:
    # don't do this in production, 'mkey?
    authorized_networks: '0.0.0.0/0'
    # the following parameter is not supported
    # require_ssl: false
    # workaround: gcloud sql instances patch myinstance --no-require-ssl
